# Generated by Django 5.0.7 on 2024-07-26 05:41

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilemanagement', '0004_rename_price_order_total_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2024, 7, 27, 5, 41, 19, 24078, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='order',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
