# Generated by Django 5.0.7 on 2024-07-26 05:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilemanagement', '0005_order_end_date_order_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2024, 7, 27, 5, 44, 50, 400177, tzinfo=datetime.timezone.utc)),
        ),
    ]
