# Generated by Django 5.0.7 on 2024-07-26 09:36

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilemanagement', '0009_remove_order_end_date_remove_order_item_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='rental_duration_months',
        ),
        migrations.AddField(
            model_name='order',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2024, 7, 27, 9, 36, 8, 225656, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='order',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='rental_duration_days',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
