# Generated by Django 5.0.7 on 2024-07-26 10:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilemanagement', '0010_remove_order_rental_duration_months_order_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2024, 7, 27, 10, 1, 20, 504886, tzinfo=datetime.timezone.utc)),
        ),
    ]
