# Generated by Django 5.0.7 on 2024-07-26 10:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilemanagement', '0011_alter_order_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2024, 7, 27, 10, 1, 41, 845994, tzinfo=datetime.timezone.utc)),
        ),
    ]
