# Generated by Django 5.0.7 on 2024-07-27 05:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilemanagement', '0013_alter_order_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2024, 7, 28, 5, 41, 41, 942155, tzinfo=datetime.timezone.utc)),
        ),
    ]
