# Generated by Django 5.0.7 on 2024-07-25 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionCamera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(choices=[('gopro', 'GoPro'), ('sjcam', 'SJCAM'), ('insta360', 'Insta360'), ('xiaomi', 'Xiaomi')], max_length=20)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('availability', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='action_camera_images/')),
            ],
        ),
        migrations.CreateModel(
            name='AudioVisualEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('equipment_type', models.CharField(choices=[('projector', 'Projector'), ('microphone', 'Microphone'), ('speaker', 'Speaker'), ('camera', 'Camera')], max_length=20)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('availability', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='audio_visual_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('camera_type', models.CharField(choices=[('dslr', 'DSLR'), ('mirrorless', 'Mirrorless'), ('compact', 'Compact'), ('action', 'Action')], max_length=20)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('availability', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='camera_images/')),
            ],
        ),
        migrations.CreateModel(
            name='CampingGear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('tent', 'Tent'), ('sleeping_bag', 'Sleeping Bag'), ('stove', 'Stove'), ('backpack', 'Backpack')], max_length=50)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('availability', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='camping_gear_images/')),
            ],
        ),
        migrations.CreateModel(
            name='CreatorGear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('camera', 'Camera'), ('microphone', 'Microphone'), ('lighting', 'Lighting'), ('tripod', 'Tripod')], max_length=50)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('availability', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='creator_gear_images/')),
            ],
        ),
        migrations.CreateModel(
            name='GamingConsole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ps5', 'PlayStation 5'), ('xbox', 'Xbox Series X'), ('switch', 'Nintendo Switch'), ('pc', 'Gaming PC')], max_length=50)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('availability', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='gaming_console_images/')),
            ],
        ),
        migrations.CreateModel(
            name='RidingGear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('helmet', 'Helmet'), ('gloves', 'Gloves'), ('jacket', 'Jacket'), ('boots', 'Boots')], max_length=50)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('availability', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='riding_gear_images/')),
            ],
        ),
        migrations.CreateModel(
            name='TrekkingGear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('binoculars', 'Binoculars'), ('trek_accessories', 'Trek Accessories'), ('trekking_shoes', 'Trekking Shoes'), ('trekking_jackets', 'Trekking Jackets'), ('trekking_backpacks', 'Trekking Backpacks')], max_length=50)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('availability', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='trekking_gear_images/')),
            ],
        ),
    ]
