# Generated by Django 5.0.7 on 2024-07-25 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WinterWear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('jacket', 'Jacket'), ('gloves', 'Gloves'), ('hat', 'Hat'), ('scarf', 'Scarf')], max_length=50)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('availability', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='winter_wear_images/')),
            ],
        ),
    ]
