# Generated by Django 5.0.7 on 2024-07-27 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0002_winterwear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiovisualequipment',
            name='equipment_type',
            field=models.CharField(choices=[('projector', 'Projector'), ('microphone', 'Microphone'), ('speaker', 'Speaker'), ('vr', 'Vr')], max_length=20),
        ),
    ]
