# Generated by Django 5.0.7 on 2024-07-27 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0003_alter_audiovisualequipment_equipment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='camera_type',
            field=models.CharField(choices=[('dslr', 'DSLR'), ('mirrorless', 'Mirrorless'), ('compact', 'Compact'), ('binocular', 'Binocular')], max_length=20),
        ),
    ]
