# Generated by Django 5.0.7 on 2024-07-27 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0004_alter_camera_camera_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatorgear',
            name='name',
            field=models.CharField(choices=[('action_cameras', 'Action Cameras'), ('wireless_mics', 'Wireless & Collar Mics'), ('professional_cameras', 'Professional Cameras'), ('vlogging_cameras', 'Vlogging Cameras'), ('mounts_accessories', 'Mounts & Accessories'), ('studio_lights', 'Studio Lights'), ('gimbals_grips', 'Gimbals and Grips')], max_length=50),
        ),
    ]
